# ============================================================
# IOC CHECKER - API KEYS CONFIGURATION
# Simpan file ini di .streamlit/secrets.toml
# JANGAN commit file ini ke Git!
# ============================================================

[api_keys]
virustotal    = "bed8db2b217a204dd0ca2246ee5000adf9b059c4c7a5516f949544f41e80e47e"
abuseipdb     = "5dd3df993ba65e46dd0418f9091165757700f6c57b7ff60a7dabf1fb88b36c3126f2e00ccb9bc6e8"
shodan        = "Na8Y2BcgtsvQfgrsAjkb6KqrBmQDngGF"
otx           = "YOUR_OTX_API_KEY"
urlscan       = "YOUR_URLSCAN_API_KEY"
greynoise     = "YOUR_GREYNOISE_API_KEY"
ipinfo        = "YOUR_IPINFO_API_KEY"
